TRAIN_DATA = [
("Babar Azam played in Karachi", {"entities":[(0,11,"PERSON"),(20,27,"LOCATION")]}),
("Virat Kohli visited Lahore", {"entities":[(0,12,"PERSON"),(21,27,"LOCATION")]}),
("Imran Khan gave speech in Islamabad", {"entities":[(0,10,"PERSON"),(28,37,"LOCATION")]}),
("Elon Musk arrived in New York", {"entities":[(0,9,"PERSON"),(23,31,"LOCATION")]}),
("Messi played in Paris yesterday", {"entities":[(0,5,"PERSON"),(18,23,"LOCATION")]}),
("Neymar went to London", {"entities":[(0,6,"PERSON"),(15,21,"LOCATION")]}),
("Bill Gates visited USA", {"entities":[(0,10,"PERSON"),(19,22,"LOCATION")]}),
("Ronaldo played in Riyadh", {"entities":[(0,7,"PERSON"),(19,25,"LOCATION")]}),
("Ahsan went to Karachi on Monday", {"entities":[(0,5,"PERSON"),(14,21,"LOCATION")]}),
("Shahid Afridi played in Lahore", {"entities":[(0,14,"PERSON"),(26,32,"LOCATION")]}),
("Virat Kohli played a match in Karachi", {"entities":[(0,12,"PERSON"),(27,34,"LOCATION")]}),
("Babar Azam scored a century in Lahore", {"entities":[(0,11,"PERSON"),(31,37,"LOCATION")]}),
("Shahid Afridi visited Islamabad on Monday", {"entities":[(0,14,"PERSON"),(23,32,"LOCATION"),(36,42,"DATE")]}),
("MS Dhoni retired from cricket in India", {"entities":[(0,8,"PERSON"),(34,39,"LOCATION")]}),
("Elon Musk launched a rocket in Texas", {"entities":[(0,9,"PERSON"),(32,37,"LOCATION")]}),
("Cristiano Ronaldo played in Riyadh yesterday", {"entities":[(0,18,"PERSON"),(29,35,"LOCATION"),(36,44,"DATE")]}),
("Lionel Messi scored two goals in Paris", {"entities":[(0,13,"PERSON"),(33,38,"LOCATION")]}),
("Neymar joined training in London on Friday", {"entities":[(0,6,"PERSON"),(25,31,"LOCATION"),(35,41,"DATE")]}),
("Imran Khan addressed a rally in Karachi", {"entities":[(0,10,"PERSON"),(33,40,"LOCATION")]}),
("Bill Gates visited Pakistan last week", {"entities":[(0,11,"PERSON"),(19,27,"LOCATION"),(28,37,"DATE")]}),

("Steve Jobs founded Apple in California", {"entities":[(0,10,"PERSON"),(25,35,"LOCATION")]}),
("Mark Zuckerberg spoke at Harvard on Monday", {"entities":[(0,16,"PERSON"),(25,32,"LOCATION"),(36,42,"DATE")]}),
("Jeff Bezos attended meeting in New York", {"entities":[(0,10,"PERSON"),(31,39,"LOCATION")]}),
("Ahsan Ali played cricket in Lahore", {"entities":[(0,9,"PERSON"),(28,34,"LOCATION")]}),
("Usman Khan traveled to Dubai yesterday", {"entities":[(0,10,"PERSON"),(23,28,"LOCATION"),(29,37,"DATE")]}),

("Shoaib Malik scored runs in Multan", {"entities":[(0,12,"PERSON"),(27,33,"LOCATION")]}),
("Rohit Sharma hit a century in Mumbai", {"entities":[(0,13,"PERSON"),(32,38,"LOCATION")]}),
("KL Rahul played in Bangalore last night", {"entities":[(0,8,"PERSON"),(22,31,"LOCATION")]}),
("Hardik Pandya joined team in Chennai", {"entities":[(0,13,"PERSON"),(29,36,"LOCATION")]}),
("David Warner played in Sydney", {"entities":[(0,12,"PERSON"),(25,31,"LOCATION")]}),

("Virat Kohli trained in Delhi today", {"entities":[(0,12,"PERSON"),(23,28,"LOCATION"),(29,34,"DATE")]}),
("Babar Azam arrived in Dubai yesterday", {"entities":[(0,11,"PERSON"),(23,28,"LOCATION"),(29,37,"DATE")]}),
("Shahid Afridi gave interview in Lahore", {"entities":[(0,14,"PERSON"),(32,38,"LOCATION")]}),
("MS Dhoni attended event in Mumbai", {"entities":[(0,8,"PERSON"),(26,32,"LOCATION")]}),
("Elon Musk visited SpaceX base in Texas", {"entities":[(0,9,"PERSON"),(32,37,"LOCATION")]}),

("Cristiano Ronaldo scored in Saudi Arabia", {"entities":[(0,18,"PERSON"),(29,42,"LOCATION")]}),
("Lionel Messi practiced in Barcelona", {"entities":[(0,13,"PERSON"),(28,37,"LOCATION")]}),
("Neymar signed contract in Paris", {"entities":[(0,6,"PERSON"),(27,32,"LOCATION")]}),
("Imran Khan spoke in Islamabad yesterday", {"entities":[(0,10,"PERSON"),(20,29,"LOCATION"),(30,39,"DATE")]}),
("Bill Gates donated funds in USA", {"entities":[(0,11,"PERSON"),(29,32,"LOCATION")]}),

("Steve Jobs inspired developers in California", {"entities":[(0,10,"PERSON"),(33,43,"LOCATION")]}),
("Mark Zuckerberg visited India on Monday", {"entities":[(0,16,"PERSON"),(27,32,"LOCATION"),(36,42,"DATE")]}),
("Jeff Bezos launched project in Seattle", {"entities":[(0,10,"PERSON"),(30,37,"LOCATION")]}),
("Ahsan Ali scored fifty in Karachi", {"entities":[(0,9,"PERSON"),(27,34,"LOCATION")]}),
("Usman Khan traveled to London last week", {"entities":[(0,10,"PERSON"),(23,29,"LOCATION"),(30,39,"DATE")]}),

("Shoaib Malik trained in Multan today", {"entities":[(0,12,"PERSON"),(24,30,"LOCATION"),(31,36,"DATE")]}),
("Rohit Sharma visited Dubai yesterday", {"entities":[(0,13,"PERSON"),(22,27,"LOCATION"),(28,36,"DATE")]}),
("KL Rahul played in Chennai", {"entities":[(0,8,"PERSON"),(22,29,"LOCATION")]}),
("Hardik Pandya gave interview in Mumbai", {"entities":[(0,13,"PERSON"),(32,38,"LOCATION")]}),
("David Warner scored in Sydney", {"entities":[(0,12,"PERSON"),(25,31,"LOCATION")]}),

("Virat Kohli met fans in Lahore", {"entities":[(0,12,"PERSON"),(24,30,"LOCATION")]}),
("Babar Azam practiced in Karachi", {"entities":[(0,11,"PERSON"),(23,30,"LOCATION")]}),
("Shahid Afridi joined event in Islamabad", {"entities":[(0,14,"PERSON"),(28,37,"LOCATION")]}),
("MS Dhoni spoke in Delhi", {"entities":[(0,8,"PERSON"),(18,23,"LOCATION")]}),
("Elon Musk visited Tesla HQ in Texas", {"entities":[(0,9,"PERSON"),(31,36,"LOCATION")]}),

("Cristiano Ronaldo trained in Riyadh yesterday", {"entities":[(0,18,"PERSON"),(29,35,"LOCATION"),(36,44,"DATE")]}),
("Lionel Messi attended match in Paris", {"entities":[(0,13,"PERSON"),(31,36,"LOCATION")]}),
("Neymar played football in London", {"entities":[(0,6,"PERSON"),(27,33,"LOCATION")]}),
("Imran Khan visited Karachi today", {"entities":[(0,10,"PERSON"),(20,27,"LOCATION"),(28,33,"DATE")]}),
("Bill Gates met students in USA", {"entities":[(0,11,"PERSON"),(28,31,"LOCATION")]}),

("Steve Jobs gave speech in California", {"entities":[(0,10,"PERSON"),(27,37,"LOCATION")]}),
("Mark Zuckerberg visited Meta office in USA", {"entities":[(0,16,"PERSON"),(35,38,"LOCATION")]}),
("Jeff Bezos attended event in New York yesterday", {"entities":[(0,10,"PERSON"),(31,39,"LOCATION"),(40,48,"DATE")]}),
("Ahsan Ali played match in Karachi today", {"entities":[(0,9,"PERSON"),(27,34,"LOCATION"),(35,40,"DATE")]}),
("Usman Khan traveled in Dubai", {"entities":[(0,10,"PERSON"),(23,28,"LOCATION")]}),

("Shoaib Malik scored runs in Lahore", {"entities":[(0,12,"PERSON"),(28,34,"LOCATION")]}),
("Rohit Sharma joined camp in Mumbai", {"entities":[(0,13,"PERSON"),(29,35,"LOCATION")]}),
("KL Rahul practiced in Bangalore", {"entities":[(0,8,"PERSON"),(22,31,"LOCATION")]}),
("Hardik Pandya played in Chennai yesterday", {"entities":[(0,13,"PERSON"),(27,34,"LOCATION"),(35,43,"DATE")]}),
("David Warner trained in Sydney today", {"entities":[(0,12,"PERSON"),(25,31,"LOCATION"),(32,37,"DATE")]}),

("Virat Kohli visited stadium in Delhi", {"entities":[(0,12,"PERSON"),(33,38,"LOCATION")]}),
("Babar Azam gave interview in Karachi yesterday", {"entities":[(0,11,"PERSON"),(29,36,"LOCATION"),(37,45,"DATE")]}),
("Shahid Afridi played charity match in Lahore", {"entities":[(0,14,"PERSON"),(39,45,"LOCATION")]}),
("MS Dhoni attended ceremony in Mumbai today", {"entities":[(0,8,"PERSON"),(32,38,"LOCATION"),(39,44,"DATE")]}),
("Elon Musk launched Tesla in Texas yesterday", {"entities":[(0,9,"PERSON"),(30,35,"LOCATION"),(36,44,"DATE")]}),

("Cristiano Ronaldo scored goal in Riyadh today", {"entities":[(0,18,"PERSON"),(31,37,"LOCATION"),(38,43,"DATE")]}),
("Lionel Messi visited academy in Paris yesterday", {"entities":[(0,13,"PERSON"),(32,37,"LOCATION"),(38,46,"DATE")]}),
("Neymar trained hard in London today", {"entities":[(0,6,"PERSON"),(24,30,"LOCATION"),(31,36,"DATE")]}),
("Imran Khan spoke at rally in Islamabad", {"entities":[(0,10,"PERSON"),(28,37,"LOCATION")]}),
("Bill Gates donated funds in Pakistan yesterday", {"entities":[(0,11,"PERSON"),(29,37,"LOCATION"),(38,46,"DATE")]}),

("Steve Jobs inspired team in California today", {"entities":[(0,10,"PERSON"),(29,39,"LOCATION"),(40,45,"DATE")]}),
("Mark Zuckerberg visited campus in India yesterday", {"entities":[(0,16,"PERSON"),(33,38,"LOCATION"),(39,47,"DATE")]}),
("Jeff Bezos launched project in Seattle today", {"entities":[(0,10,"PERSON"),(32,39,"LOCATION"),(40,45,"DATE")]}),
("Ahsan Ali scored fifty in Karachi yesterday", {"entities":[(0,9,"PERSON"),(27,34,"LOCATION"),(35,43,"DATE")]}),
("Usman Khan traveled to London today", {"entities":[(0,10,"PERSON"),(23,29,"LOCATION"),(30,35,"DATE")]})


]